# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:year/:title/

# Setup
title:            Igor Matuszewski
description:      Through game programming and more
baseurl:          '/'

paginate: 5

author:
  name:           'Igor Matuszewski'

gems: [jekyll-paginate, jekyll-gist]
